### ISSUE TITLE
Add .rubocop.yml that is compatible with hound

### ISSUE THREAD

**Issue by edwinvdgraaf** [hkrutzer/roger_scsslint#5]
Or remove hound, I'm guessing that would be a bad experience, theres a sample config for hound.

See https://gist.github.com/skisulli/10758684

**Comment by hkrutzer** [comment]
That file is not actually compatible with default Hound settings, e.g.:
```
StringLiterals:
  # Valid values (denoting the preferred quote delimiters) are:
  # single_quotes, double_quotes
     EnforcedStyle: single_quotes
     Enabled: true
```

Apparently, this is [more complex](https://github.com/e2/hound-tools).
